/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AudioPermission: typeof import('./src/components/AudioPermission.vue')['default']
    Charts: typeof import('./src/components/Charts.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    NewOrder: typeof import('./src/components/NewOrder.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snack: typeof import('./src/components/Snack.vue')['default']
  }
}
